server:
  port: 8081

audit-service:
  base-url: http://${AUDIT_HOST:localhost}:${AUDIT_PORT:8082}

spring:
  datasource:
    username: payments
    password: payments
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payments
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

